### PR TITLE
Add detection for EdgeOS on UniFi Security Gateway

### PR DESCRIPTION
**Pull request by AdamVig**
Relates to #48.

### CODE REVIEW

**Comment by rs** [comment]
Does the rest of the install just work with that?

**Comment by AdamVig** [comment]
@rs Yes, I should have mentioned that I ran `install.sh` with this modification on my UniFi Security Gateway and it seems to work correctly.

**Comment by rs** [comment]
I’m surprised, there is a whole thread about USG on #45. Are you sure it does also survive a reboot?

**Comment by AdamVig** [comment]
Good question. I rebooted the router, SSHed in, and ran `./config/nextdns status`, which returned `running`. Seems like it works fine. Thanks for merging this!

**Comment by rs** [comment]
Wow, easy then... thx for testing and PR.

**Comment by ChrisColotti** [comment]
Reboot vs upgrade / re-provision is different.  Most changes will survive a reboot but will get wiped on a re-provision.  You can test by forcing a re-provision via the controller.

**Pull request merged**
