### PR TITLE
Embed Let's Encrypt root certificates

### PR DESCRIPTION
**Pull request by vincentbernat**
This avoids loading all the system root certificates. On my system,
3MB of memory are saved doing this. However, this comes with a high
risk as if we need to switch away from Let's Encrypt without careful
planning, not-up-to-date clients won't be able to connect at all.

This could be solved by:
 - using a flag to not force use of root system certificates
 - load root system certificates in case of bad certificate error

I think the second option is doable. However, are 3MB of savings worth
the complexity? I thought it would have been possible to save more.

### CODE REVIEW

**Comment by vincentbernat** [comment]
We could even embed the intermediate certificate to reduce the compute cost on client side. This would be safe as we would still embed the root certificate.

**Comment by rs** [comment]
We are moving away from letsencrypt soon.

**Comment by vincentbernat** [comment]
Fixing #546 was a side effect of this PR. Initially, it was mostly to reduce the memory usage. It should also reduce the signature verification, but with #547, this is not really important anymore.

**Comment by vincentbernat** [comment]
This is not needed anymore: LE is not used as an authority anymore.

**Pull request closed without merging**
