### PR TITLE
Add support for UXG series of Unifi product

### LINKED ISSUE #889: Support for Unifi Gateway Lite
New UI Gateway dropped and the CLI doesn't seem to detect it as a Unifi device. Looks like the client currently looks for the `/data/unifi` path ([relevant line](https://github.com/nextdns/nextdns/blob/master/router/ubios/setup.go#L21)) but on my device I have:
```
# ls /data/
dpi-tracer/  udapi-config/  ui-db/  uxgpro-setup/  wifiman/
```

However, the CLI does install correctly, but conflicts with the `dnsmasq` on port 53 from `ubios-udapi-server`. Are there any plans to support this device?

Update: Looks like I only needed to create the dir `/data/unifi` and everything worked.

### PR DESCRIPTION
**Pull request by rs**
Fixes #889

### CODE REVIEW

**Comment by rs** [comment]
You did not test the snapshot. Please make sure to copy the whole command: 

```
NEXTDNS_VERSION=pr-899/SNAPSHOT-efee3d1 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
```

**Comment by wprivera** [comment]
Thank you for the reply RS.  I am not a programmer. Please forgive my ignorance. I don't know what running the "test snapshot" will do. If you have time, would you please explain?

**Comment by rs** [comment]
This is to test an unreleased version to validate it is working before merging it.

**Comment by wprivera** [comment]
root@UXG-Pro:~# nextdns log
Jan 04 19:55:13 UXG-Pro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Configuring ubios router: UDM "Content Filtering" feature is enabled. Please disable it to use NextDNS
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Starting NextDNS 0.0.0-SNAPSHOT-efee3d1/linux on localhost:53
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Listening on TCP/[::1]:53
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Listening on UDP/127.0.0.1:53
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Listening on TCP/127.0.0.1:53
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Listening on UDP/[::1]:53
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Starting mDNS discovery
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Startup failed: proxy: tcp: listen tcp [::1]:53: bind: address already in use
Jan 04 19:55:13 UXG-Pro nextdns[27110]: Error: proxy: tcp: listen tcp [::1]:53: bind: address already in use
Jan 04 19:55:13 UXG-Pro systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 19:55:13 UXG-Pro systemd[1]: nextdns.service: Failed with result 'exit-code'.
root@UXG-Pro:~#

**Comment by rs** [comment]
What do you get for `nextdns config`

**Comment by rs** [comment]
Snapshot

**Comment by brianmulford** [comment]
I installed this version on my UXG lite and works as expected.

**Comment by rs** [comment]
Thanks for your help

**Comment by wprivera** [comment]
I ran the snapshot again with Ad Blocking and Content Filtering disabled on the Unifi console. All is working well. I can see traffic identified be each network device name again. Thanks again for your help.

root@UXG-Pro:~# nextdns log
Jan 25 21:33:20 UXG-Pro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Jan 25 21:33:20 UXG-Pro nextdns[425761]: Starting NextDNS 0.0.0-SNAPSHOT-efee3d1/linux on localhost:5342
Jan 25 21:33:20 UXG-Pro nextdns[425761]: Starting mDNS discovery
Jan 25 21:33:20 UXG-Pro nextdns[425761]: Listening on TCP/[::1]:5342
Jan 25 21:33:20 UXG-Pro nextdns[425761]: Listening on TCP/127.0.0.1:5342
Jan 25 21:33:20 UXG-Pro nextdns[425761]: Listening on UDP/[::1]:5342
Jan 25 21:33:20 UXG-Pro nextdns[425761]: Listening on UDP/127.0.0.1:5342
Jan 25 21:33:25 UXG-Pro nextdns[425761]: Setting up ubios router
Jan 25 21:33:25 UXG-Pro nextdns[425761]: Activating
Jan 25 21:33:25 UXG-Pro nextdns[425761]: Connected [2a07:a8c1::]:443 (con=22ms tls=61ms, TCP, TLS13)
Jan 25 21:33:25 UXG-Pro nextdns[425761]: Connected [2001:19f0:ac01:170:5400:2ff:fec8:72c8]:443 (con=22ms tls=39ms, TCP, TLS13)
Jan 25 21:33:25 UXG-Pro nextdns[425761]: Switching endpoint: https://dns.nextdns.io#209.209.57.165,104.238.181.28,2a0e:6901:410:25:5054:ff:fe1c:7c81,2001:19f0:ac01:170:5400:2ff:fec8:72c8
root@UXG-Pro:~#

**Comment by adamtmitchell** [comment]
Does this also include support for the Cloud Gateway Ultra? I'd test it myself but I think we're probably another 6-8 weeks from the device reaching Australia for me to replace my Dream Machine.

**Comment by rs** [comment]
I don’t think anyone reported it working or not working yet.

**Comment by cpfowler** [comment]
> Does this also include support for the Cloud Gateway Ultra? I'd test it myself but I think we're probably another 6-8 weeks from the device reaching Australia for me to replace my Dream Machine.

Just got it working on my UCG-Ultra.
Straight forward, no problems or issues.
It even paused the setup and told me to turn off Unifi's built in option for ad blocking, knew when I disabled it, and continued setup.
Devices in my NextDNS log even have matching names for what I called them in Unifi, which wasn't a thing for my now replaced USG-3P.

Not sure where to post this info to get the supported devices list updated, though.

**Pull request merged**
