### PR TITLE
ci: fix commit author in OpenWRT flow

### PR DESCRIPTION
**Pull request by mad-it**
This PR fixes the issue with checks failing in OpenWRT.

There were 2 possibilities in to solve these issues:

Option 1: Hardcode everything to `Olivier Poitrey <rs@nextdns.io>`
Option 2: Define the author based on author of the commit.

I opted for option 2 because this is more in line with the reality of the commit history.

On that note, I don't know if OpenWRT checks if the author is the same as `PKG_MAINTAINER` which is configured in the package. If they do, we might need to revisit this, because I have noticed the following commit in the commit history:
```
commit 9cdc17eb5451a979a993c7a89085a4e1f7817795
Author: Olivier Poitrey <rs@xxxxxxx.net>
Date:   Mon May 4 16:24:42 2020 -0700

Update issue templates
```

As you can see, the email(domain redacted for your privacy even though its a public git repo) is not in line with what is configured OpenWRT's `PKG_MAINTAINER`.

### CODE REVIEW

**Comment by hnyman** [comment]
> if OpenWRT checks if the author is the same as PKG_MAINTAINER

No, it doesn't.

PRs can naturally be authored by anybody, and then the Maintainer should verify the PR and mark his acceptance to the PR discussion thread.

Put it simply,
* if the PR is authored/submitted by the maintainer, the commit access holders usually merge the PRs quickly
* if the PR is authored by somebody else, the PR usually waits until the maintainer says his ok to the PR

**Comment by hnyman** [comment]
Additional comment:
It would be good to mark a possible release to a stable OpenWrt branch (like 19.07) as a backport, cherry-pick, whatever. But indicate clearly in the"non-master" PR that it is intended for the stable branch and that the same stuff has been submitted/merged into master.

(There are sometimes erroneous new stuff PRs for stable branches, so cherry-picks or similar are preferred.)

**Comment by rs** [comment]
Is it also possible to signoff the commit? That’s the second CI complain.

**Comment by mad-it** [comment]
> Is it also possible to signoff the commit? That’s the second CI complain.

This has already been taken care of in the current PR.

Other then that, I will split the creating of PR's towards OpenWRT in 2 different steps:

- master
- back ported branch(es) e.g. 19.07

This will allow us to configure anything "non-master" differently like @hnyman proposed.

**Comment by mad-it** [comment]
@rs The change has been implemented but to be honest I'm not really happy with how complex it has become. 

The reason it became so complex is to be able to add a nice comment to the PR for stable(backport) branches.
As you can see in https://github.com/mad-it/packages/pull/10 its a PR for a stable branch referring to the PR towards master. 
This is what I interpreted from: 
> But indicate clearly in the"non-master" PR that it is intended for the stable branch and that the same stuff has been submitted/merged into master.

This could be greatly simplified if we would replace the comment in the stable PR with something like `A separate PR towards master has also been created`.

I would love to hear your thoughts on this.

**Comment by hnyman** [comment]
One option would be: 
Prepend the PR title with "[19.07]"  so that it is clear that it is for the other branch
Example:
`[19.07] vpn-policy-routing: support phys-dev policies `
https://github.com/openwrt/packages/pull/12080

Providing a link to the other PR is not quite that necessary. Nice and informative, but adds maybe too much complexity for you

**Comment by mad-it** [comment]
@hnyman Thanks a bunch for pointing out that option. It made things much simpler.

@rs PR is ready for review once again. This should fix all the CI issue seen in previous release + addresses @hnyman concern in regards to making a distinction between "master" and "non-master" releases.

**Comment by rs** [comment]
Thx!

**Comment by hnyman** [comment]
The two PRs showed green on the automatic testing at OpenWrt paclages repo.
I merged them.

**Comment by mad-it** [comment]
@hnyman I have a small question. How is the release process of the stable releases? As you stated in your previous comment, the PR's were green and were merged. I tried finding updating the package hoping I would find the latest nextdns version but I havent found it yet.

```
BusyBox v1.30.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 19.07.2, r10947-65030d81f3
 -----------------------------------------------------
root@OpenWrt:~# opkg update
root@OpenWrt:~# opkg find nextdns
nextdns - 1.4.23-1 - Official NextDNS DNS over HTTPS Proxy.
 root@OpenWrt:~# opkg status nextdns
Package: nextdns
Version: 1.4.23-1
Depends: libc, ca-bundle
Status: install user installed
Architecture: arm_cortex-a9_vfpv3
Installed-Time: 1587565334
```

**Comment by hnyman** [comment]
> Architecture: arm_cortex-a9_vfpv3

You are using an abandoned architecture, so the packages have not been compiled for that:

arm_cortex-a9_vfpv3 was changed to arm_cortex-a9_vfpv3-d16 in mid-April to accommodate for the weakest CPU in the mvebu family Armada 370 found in the original WRT1900AC. The change in the architecture definitions will be reflected in 19.07.3 when that gets done. Until then you need to manually download the packages (or try changing the definition in distfeed.conf)

image

The updated packages is found for pretty much all other architectures except the one that you are using.

E.g.
https://downloads.openwrt.org/releases/packages-19.07/arm_cortex-a9_vfpv3-d16/packages/nextdns_1.5.8-1_arm_cortex-a9_vfpv3-d16.ipk
(you should be able to download and use it quite normal.

Other examples (not for you):

https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/packages/nextdns_1.5.8-1_mips_24kc.ipk

Here the yesterday's bump has not yet been compiled:
https://downloads.openwrt.org/releases/packages-19.07/arm_cortex-a15_neon-vfpv4/packages/nextdns_1.5.7-1_arm_cortex-a15_neon-vfpv4.ipk
http://buildbot.openwrt.org/openwrt-19.07/packages/grid

**Comment by mad-it** [comment]
Thanks for the details explanation. Went with updating the distfeed.conf.

**Pull request merged**
